language: node_js

branches:
  only:
    - master

cache: yarn

jobs:
  include:
    - stage: test
      node_js: "14"
    - stage: release
      node_js: "14"
      script: skip # Skip running "yarn test" again
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn run semantic-release
